name: Update Route Status

on:
  schedule:
    # Run every day at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd scripts
          pip install -r requirements.txt

      - name: Fetch route status
        run: |
          cd scripts
          python fetch_route_status.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet public/data/route_status.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/data/route_status.json
          git commit -m "Update route status data

🤖 Automated update from IFCN Madeira website"
          git push
